### ISSUE TITLE
RTL for API level 15 and up

### ISSUE THREAD

**Issue by royarzun** [royarzun/StockHawk#6]
RTL not working for App running in devices below API level 17

**Comment by royarzun** [comment]
I will try solving this issue using [Viewcompat class](https://developer.android.com/reference/android/support/v4/view/ViewCompat.html#setLayoutDirection%28android.view.View, int%29)

**Comment by royarzun** [comment]
Too much trouble... Will fix the RTL support for Android API level above 16. I will reopen this issue if the app does not meet the requirements for the project.

**Comment by Tfik** [comment]
did u get the solution
